# Makefile: Makefile to compile module
# Copyright (C) 2032 CESNET z. s. p. o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#

TOP_LEVEL_ENT=PMCI_TOP
SYNTH=quartus
DEVICE=AGILEX

.PHONY: all
all: comp

include ../../../../../../../conf/Makefile
